name: Build Python Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name main main.py
        
    - name: Verify config.yaml exists
      run: |
        if (!(Test-Path "config.yaml")) {
          Write-Error "config.yaml not found in repository"
          exit 1
        }
        Write-Host "config.yaml found and will be included in package"
        
    - name: Create zip package
      run: |
        cd dist
        copy ..\README.md .
        copy ..\LICENSE .
        copy ..\CONFIG_README.md .
        copy ..\config.yaml .
        if (Test-Path "..\capture") { xcopy ..\capture capture\ /E /I /Y } else { mkdir capture }
        powershell Compress-Archive -Path main.exe,README.md,LICENSE,CONFIG_README.md,config.yaml,capture -DestinationPath VMware-EventID-2004-Detector.zip
        
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/VMware-EventID-2004-Detector.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VMware-EventID-2004-Detector
        path: dist/VMware-EventID-2004-Detector.zip